### ISSUE TITLE
Windows Run Error

### ISSUE THREAD

**Issue by rzellem** [hpparvi/ldtk#24]
I installed Python using the Windows installation via the Microsoft Store, and I'm getting the following error:

```
C:\Users\artif\Downloads\EXOTIC-0.44.0\EXOTIC-0.44.0>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\artif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ldtk\__init__.py", line 21, in <module>
    from .ldtk import LDPSetCreator, LDPSet, load_ldpset
  File "C:\Users\artif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ldtk\ldtk.py", line 33, in <module>
    from .client import Client
  File "C:\Users\artif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ldtk\client.py", line 32, in <module>
    from .core import ldtk_root, TEFF_POINTS, LOGG_POINTS, Z_POINTS, is_inside, SpecIntFile, message
  File "C:\Users\artif\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ldtk\core.py", line 48, in <module>
    ldtk_root  = os.getenv('LDTK_ROOT') or join(os.getenv('HOME'),'.ldtk')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
>>>
```

According to the interwebs, this might be the fix to this issue (but will need to be tested on Mac/Unix to ensure compatibility): https://stackoverflow.com/questions/47400620/expected-str-bytes-or-os-pathlike-object-not-list

**Comment by jpl-jengelke** [comment]
Suggested change:
```
import pathlib
...
sys_home = os.getenv('HOME', os.getenv('HOMEPATH'))
sys_home = str(pathlib.Path('temp')) if sys_home is None else sys_home
ldtk_root  = os.getenv('LDTK_ROOT') or join(sys_home, '.ldtk')
```
Note that Pathlib will automatically cast to a Windows or a POSIX path based on underlying system.

**Comment by hpparvi** [comment]
Hi,

This issue is the same as #22 and should be fixed now. However, I can't test if the fix works (I'm not a Windows user), so I'd be happy if you could pull the latest changes and give it a try.

Cheers,
Hannu

**Comment by jpl-jengelke** [comment]
Hi @hpparvi, 

Sorry, I made a couple additional minor changes to ensure it works and not to limit other users to Python 3.4+. We will test when it's pulled into master. 

Thank you, 

@jpl-jengelke

**Comment by hpparvi** [comment]
Thanks, @jpl-jengelke! I've merged the changes and they look ok to my eye (and don't break anything in Linux.)

**Comment by rzellem** [comment]
hi @hpparvi - I can confirm that the code on the master branch works on my Windows PC!!! Thank you for fixing this so quickly! Any estimate of when it will be released?

**Comment by hpparvi** [comment]
Great news, @rzellem! I've now updated the package in PyPI and created a new release in GitHub.

**Comment by rzellem** [comment]
Thank you, @hpparvi !!!
